In [1]:
# Vector addition & subtraction
from numpy import array as ar
x = ar([4, 5])
y = ar([4*4/4, 7+65])
x+y
# len(x) must be equal to len(y)
# No Strings as elements!
# dtype('<U32') are only supported!

array([ 8., 77.])

In [2]:
x-y
# Lists, unlike numpy arrays, don't need lengths to be same.
# But they don't do vector operators!!!

array([  0., -67.])

In [3]:
x = [4, 5, 6]
y = [7, 8, 9]
x+y
# They just concatenate rather than adding.

[4, 5, 6, 7, 8, 9]

In [4]:
x-y
# You cannot subtract lists.

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [5]:
x = ar([4, 5])
y = ar([4*4/4, 7+65])
from numpy import concatenate as ct
ct((x, y)) # Remember two parenthesis

array([ 4.,  5.,  4., 72.])

In [6]:
print('Sum of arrays:', x+y)

Sum of arrays: [ 8. 77.]


In [7]:
# Scalar Vector multiplication & divison
x = ar([1,2,3])
4*x

array([ 4,  8, 12])

In [8]:
x/4
# Beware of Python 2!
# For Python 2.x, integer division is used when you use the operator / on scalars.
# For example, 5/2 gives you 2. You can avoid this problem by adding decimals to the
# integer, i.e., 5.0/2. This gives you 2.5.

array([0.25, 0.5 , 0.75])

In [9]:
# Python doesn't really have any syntax for multi-line comments.
# There's a way.
# Credits: https://stackoverflow.com/a/7696966
''' 
You can use triple-quoted strings. When they're not a docstring (the first thing in a class/function/module)
, they are ignored.
'''

print("https://en.wikipedia.org/wiki/Docstring")

https://en.wikipedia.org/wiki/Docstring


In [10]:
# Scalar vector addition
# This is not a mathematical notation.
x+2

array([3, 4, 5])

In [11]:
y = print(x)
y+2
# Fail! List here.

[1 2 3]


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [12]:
# Playing with elementwise operations
import numpy as np
p_initial = np.array([22.15, 89.32, 56.77])
p_final = np.array([23.05, 87.32, 53.13])
r = (p_final - p_initial) / p_initial
r

array([ 0.04063205, -0.0223914 , -0.06411837])

In [13]:
import numpy as np
p_initial = [22.15, 89.32, 56.77]
p_final = [23.05, 87.32, 53.13]
r = (p_final - p_initial) / p_initial
r
# Lists doesn't support these.

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [14]:
# Linear Combination of Vectors
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
alpha = -0.5
beta = 1.5
c = alpha*a + beta*b
c
# This can be written in another form.

array([4., 5.])

In [15]:
'''
Define a function named lincomb with arguments coeff & vectors
Consider the length of first entry of vectors to be n
Consider "comb" as a zero vector of length n
for i in range of length of vectors
    add coeff*vectors
    return comb
'''
print("These are comments")

These are comments


In [16]:
# How does this pseudocode work?
coeff = [a, b]
vectors = [alpha, beta]
n = 2
comb = np.zeros(2)
# We have a zero vector of size 2 here.
# a*alpha
comb += coeff[0]*vectors[0]
comb

array([-0.5, -1. ])

In [17]:
coeff

[array([1, 2]), array([3, 4])]

In [18]:
# +b*beta
comb += coeff[1]*vectors[1]
# There is no coeff[2] or vectors[2]
comb

array([4., 5.])

In [19]:
def lincomb(coeff, vectors):
    n = len(vectors[0])
    comb = np.zeros(n)
    for i in range(len(vectors)):
        comb += coeff[i]*vectors[i]
    return comb

In [20]:
lincomb([alpha, beta], [a,b])

array([4., 5.])

In [21]:
# Working of sum keyword
numbers = [1,2,3,4,5,1,4,5]
  
# start parameter is not provided
Sum = sum(numbers)
print(Sum)
  
# start = 10
Sum = sum(numbers, 10)
print(Sum)

25
35


In [22]:
# There is still another way!
def lincom(coef, vectors):
    return sum(coef[i]*vectors[i] for i in range(len(vectors)))

In [23]:
lincom([alpha, beta], [a,b])

array([4., 5.])

In [24]:
# For scalar!
def lincom(coef, vectors):
    return sum(coef*vectors[i] for i in range(len(vectors)))

In [25]:
lincom([alpha, beta], [a,b])

array([-2.,  9.])

In [26]:
# So, how did this work?
'''
Defining function with arguments
return a value of sum of (coef[i]*vectors[i]) when i is in range of size of vectors'''

print("Method?")

Method?


In [27]:
# Check distributive property
def distribut(a, b, const):
    print("LHS const*(a+b): ", const*(a+b))
    print("\nRHS const*a+const*b: ", lincom(const, [a, b]))

In [28]:
from numpy import array as ar
a = ar([1, 2])
b = ar([3, 4])
const = ar([40])
d = distribut(a, b, const)
distribut(a, b, const)

LHS const*(a+b):  [160 240]

RHS const*a+const*b:  [160 240]
LHS const*(a+b):  [160 240]

RHS const*a+const*b:  [160 240]


In [29]:
const[0]*a+const[0]*b

array([160, 240])

In [30]:
const[0]*a

array([40, 80])

In [31]:
c = (a+b)*const
c

array([160, 240])

In [32]:
c == d

array([False, False])

In [33]:
# Inner Product
np.inner(a, b)

11

In [34]:
# Another method for Inner Product
a @ b

11

In [35]:
# Example - Net present value
c = np.array([0.1,0.1,0.1,1.1]) #cash flow vector
n = len(c)
r = 0.05 #5% per-period interest rate
d = np.array([(1+r)**-i for i in range(n)])
# In the fifth line, to get the vector d we raise the scalar 1+r element-wise to the powers
# given in the range range(n) which expands to 0, 1,2, ..., n-1, using list comprehension.
NPV = c @ d
print(NPV)

1.236162401468524


In [36]:
# Complexity of Vector Computations
# Floating point operations
a = np.random.random()
b = np.random.random()
lhs = (a+b) * (a-b)
rhs = a**2 - b**2
print(lhs - rhs)
# There are very small floating point round-off errors

2.7755575615628914e-17


In [37]:
# Time Complexity
# You can time a Python command using a time package
# The timer is not very accurate for small times, say microseconds
# If you run the command more than once; it can be a lot faster on the second or
# subsequent runs.
from time import time
a = np.random.random(10**5)
b = np.random.random(10**5)
start = time()
a @ b
end = time()
print(end-start)

0.00699615478515625


In [38]:
start = time()
a @ b
end = time()
print(end-start)

0.0


In [39]:
start = time()
(a @ b)**26
end = time()
print(end-start)

0.0


In [40]:
# Creating sparse vectors
# Functions for creating and manipulating sparse vectors are contained in the Python package scipy.sparse
# 7 classes of sparse structure in the package
# Sparse vectors are stored as sparse matrices, i.e., only the nonzero elements are stored
'''
The scipy.sparse.coo_matrix() function create a sparse matrix from three arrays that 
specify the row indexes, column indexes and values of the nonzero elements.

coo_matrix((data, (i, j)), [shape=(M, N)])

To construct from three arrays:
data[:] the entries of the matrix, in any order

i[:] the row indices of the matrix entries

j[:] the column indices of the matrix entries

Where A[i[k], j[k]] = data[k]. When shape is not specified, it is inferred from the index arrays
'''


'''
A better understanding for myself
coo_matrix((data, (i, j)), shape=(m, n))

Consider data = [5, 4, 7, 3]
And i, j be two matrices as
i = [0, 3, 1, 2]
j = [0, 3, 0, 1]

When you use this function, you are essentially stating that data[i] entry should be at place i[i]*j[i], here [i] states index
for data[1] = 4
It is placed at i[1]*j[1] = 3*3
In coo_matrix, the entry of 3*3 is 4.

As for shape, it is the size, (if specified). Else it would be inferred from index arrays.
'''

data = [5, 4, 7, 3]
i = [0, 3, 1, 2]
j = [0, 3, 0, 1]
from scipy.sparse import coo_matrix
coo_matrix((data, (i, j)), shape=(4, 4))

<4x4 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [41]:
# Represent this as an array
coo_data = coo_matrix((data, (i, j)), shape=(4, 4)).toarray()
coo_data

array([[5, 0, 0, 0],
       [7, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 0, 4]])

In [42]:
# Finding Maximum value in an array
np.max(coo_data)

7

In [43]:
# Minimum value in an array
np.min(coo_data)

0

In [44]:
# Example
I = np.array([4,7,8,9])
J = np.array([0,0,0,0])
V = np.array([100,200,300,400])
A = coo_matrix((V,(I,J)),shape = (10000,1))
A

<10000x1 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [45]:
A.toarray()

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [46]:
A.todense()

matrix([[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]])

In [47]:
# toarray returns an ndarray; todense returns a matrix. If you want a matrix, use todense; otherwise, use toarray.
# Credits: https://stackoverflow.com/a/30416739
print("https://stackoverflow.com/a/30416739")

https://stackoverflow.com/a/30416739
