In [1]:
# Recommended way to represent vectors in Python is to use numpy array.
# We can initialize numpy arrays from Python list.
# A major advantage of numpy arrays is their ability to perform linear algebra operations

from numpy import array
k = array([-1.2, 42.5, 114, 0, 5, 0.0])
len(k)

6

In [2]:
# Simplest way to represent vectors in Python is using a list structure.
x = [-1.2, 42.5, 114, 0, 5, 0.0]
len(x)

6

In [3]:
y = (1, 2)
# y is a tuple containing two scalars. Neither a list nor a vector.

In [4]:
# Indexing
x[4]

5

In [5]:
k[3]

0.0

In [6]:
# Index of last element of array k
k[-1]

0.0

In [7]:
# Assigning
y = x

In [8]:
# Copying instead of assigning
m = x.copy()

In [9]:
# Changing elements using Indexing on LHS of assignment statement
x[2] = 40
x

[-1.2, 42.5, 40, 0, 5, 0.0]

In [10]:
y

[-1.2, 42.5, 40, 0, 5, 0.0]

In [11]:
m

[-1.2, 42.5, 114, 0, 5, 0.0]

In [12]:
k = y.copy()
k[1] = "Off"
k

[-1.2, 'Off', 40, 0, 5, 0.0]

In [13]:
f = k.copy()

In [14]:
# Vector Equality with numpy array.
# Element wise comparison is done.
f == k

True

In [15]:
f[0] = "Null"
f == k

False

In [16]:
# Vector Equality with list structures
y == x

True

In [17]:
y[0] = "Hack"
y == x

True

In [18]:
m[4] = 4+4
y == m

False

In [19]:
a = [4, 4.5, 5, 5.5]
b = [7, 6]
c = [4, 46, 5, 56]
d = array([46, 48])
e = array([4, 46, 5, 55])
a == b

False

In [20]:
a == c

False

In [21]:
b == c

False

In [22]:
a == e

array([ True, False,  True, False])

In [23]:
a == d
# I get a warning here when numpy array & list of different lengths are used
# It seems numpy is preventing invalid operations.
# Deprecated relation.

C:\Users\Test\AppData\Local\Temp/ipykernel_6748/144689061.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a == d


False

In [24]:
d == e
# I get a warning here when numpy arrays of different lengths are used.
# It seems numpy is preventing invalid operations.
# Deprecated Relation

C:\Users\Test\AppData\Local\Temp/ipykernel_6748/2063342501.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  d == e


False

In [25]:
e == e

array([ True,  True,  True,  True])

In [26]:
x = [46]
y = 46
x == y

False

In [27]:
x[0] == 46
# This time it follows similar to mathematical notation of Vectors.

True

In [28]:
x = array([46])
x == y
# numpy seems to follow mathematical notation of Vectors

array([ True])

In [29]:
# Stacked vectors using list structures
fst = [1, 2, 3]
sec = [4, 5, 6]
from numpy import concatenate
mix = concatenate((fst, sec))
mix

array([1, 2, 3, 4, 5, 6])

In [30]:
# Stacked vectors using numpy
fst = array([1, 2, 3])
sec = array([4, 5, 6])
from numpy import concatenate
mix = concatenate((fst, sec))
mix

array([1, 2, 3, 4, 5, 6])

In [31]:
# Stacked vectors using both
fst = [1, 2, 3]
sec = array([4, 5, 6])
from numpy import concatenate
mix = concatenate((fst, sec))
mix

array([1, 2, 3, 4, 5, 6])

In [32]:
# DANGER: These are not stacked vectors.
tst1 = (fst, sec)
tst1

([1, 2, 3], array([4, 5, 6]))

In [33]:
# DANGER: These are not stacked vectors.
tst_2 = [fst, sec]
tst_2

[[1, 2, 3], array([4, 5, 6])]

In [34]:
# DANGER: These are not stacked vectors.
tst3 = array([fst, sec])
tst3

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# Slicing/Subvectors
k = array(["First", 1, 2, "Maybe 3?", "0", 46+444, 4*4])
k[1:3]
# It seems data types output is trigged when multiple data types and numpy are used

array(['1', '2'], dtype='<U11')

In [36]:
m = [4, 5, 6, 7, 8, "Sleep"]
m[:-1]
# Data types not showing up here.

[4, 5, 6, 7, 8]

In [37]:
m[2:4] = array(["shift", "12:50AM", "A String"])
m

[4, 5, 'shift', '12:50AM', 'A String', 8, 'Sleep']

In [38]:
m = array([46, 1, 2, 3, 44, "What?"])
m[:-1]

array(['46', '1', '2', '3', '44'], dtype='<U11')

In [39]:
m = array([44, 4.0, -7.5, "jupyter", "Wake up"])
m[1] = 44.54
m[1:-1]

array(['44.54', '-7.5', 'jupyter'], dtype='<U32')

In [40]:
m[0:]

array(['44', '44.54', '-7.5', 'jupyter', 'Wake up'], dtype='<U32')

In [41]:
m[3:4] = ["Why?", "Int", "No it was string"];
# Gives a error since lengths are not same
# It seems Jupyter stops running code here due to errors.

ValueError: could not broadcast input array from shape (3,) into shape (1,)

In [42]:
m[4] = 44
m[0] == m[4]

True

In [43]:
print(m[0:])
# Removes the keyword array

['44' '44.54' '-7.5' 'jupyter' '44']


In [44]:
# Incremented Indexing
m[1:2:4]

array(['44.54'], dtype='<U32')

In [45]:
m[1:4:2]
# This is what we want [start, end, increment]
# Has Exceptions bottom.

array(['44.54', 'jupyter'], dtype='<U32')

In [46]:
m[-1] = "Useless code"
m[::-1]
# Reversed vector

array(['Useless code', 'jupyter', '-7.5', '44.54', '44'], dtype='<U32')

In [47]:
m[-1] = "Sleep fast"
m[0::]

array(['44', '44.54', '-7.5', 'jupyter', 'Sleep fast'], dtype='<U32')

In [48]:
x = array([2, 3, 4, 5])
y = array(["Time", 2, "2am?", "Sleep"])
x[1:]-x[:-1]
# [3,4,5] - [2,3,4,5]

array([1, 1, 1])

In [49]:
x = array([2, 3, 4, 5, "Wait"])
y = array(["Time", 2, "2am?", "Sleep"])
x[1:]-x[:-1]
# ERROR:
# Strings cannot be subtracted in arrays.

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [50]:
m = x[1:-1]
x - m
# ERROR:
# No matter even if they are same.

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [53]:
x = ["T", "Y"]
y = ["Y", "J"]
z = x
a = x.copy()
z-x
# List subtraction doesn't exist!

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [54]:
# Vector of first differences
# d = x(index=i+1) - x(index=i) for i = 1,2,...n-1
x = array([42, 4, 5, 75, 51.15, -5, -2.4, 5*7, 7+86])
x[1:]-x[:-1]

array([-38.  ,   1.  ,  70.  , -23.85, -56.15,   2.6 ,  37.4 ,  58.  ])

In [56]:
x[-1]-x[7]

58.0

In [57]:
array([x[-1]-x[7]])
# It seems floating point zeros are not shown when in a numpy array

array([58.])

In [58]:
x = [2, 3, 4, "Py"]
y = [4, 4*4+4]
z = ["Sure", "Jpy", 46*4]
# This is already covered in topic of Non-Stacked vectors
list_of_vectors=[x, y, z]
tuple_of_vectors=(x, y, z)
list_of_vectors

[[2, 3, 4, 'Py'], [4, 20], ['Sure', 'Jpy', 184]]

In [59]:
list_of_vectors[2]

['Sure', 'Jpy', 184]

In [60]:
list_of_vectors[2][1]

'Jpy'

In [61]:
tuple_of_vectors

([2, 3, 4, 'Py'], [4, 20], ['Sure', 'Jpy', 184])

In [62]:
tuple_of_vectors[2]

['Sure', 'Jpy', 184]

In [63]:
tuple_of_vectors[2][1]
# Make sure to remember these aren't stacked/block vectors.
# These are either tuples (for this example) or lists/arrays [(array of arrays) or (list of arrays) or (list of lists)]

'Jpy'

In [64]:
# Zero Vectors
from numpy import zeros
zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
m = [0, 0, 0]
m == zeros(3)

array([ True,  True,  True])

In [66]:
# We don't have any direct keyword for unit vectors.
# We create e(index=i), the ith unit vector of length n using index i.
# Maybe using zeros?
i = 2
n = 4
x = zeros(n)
x[i] = 1
x

array([0., 0., 1., 0.])

In [68]:
# Ones vector
from numpy import ones
t = ones(7)
t

array([1., 1., 1., 1., 1., 1., 1.])

In [69]:
print(t)

[1. 1. 1. 1. 1. 1. 1.]


In [71]:
from numpy import random
random.random(4)

array([0.70452782, 0.89760782, 0.48855475, 0.11976593])